services:
  fakeout_streaming:
    build: .
    image: fakeout
    volumes:
      - ./_creds:/app/_creds
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/_creds/GOOGLE_APPLICATION_CREDENTIALS.json
    command: python src/main.py
